### ISSUE TITLE
Cannot run app in API level 23

### ISSUE THREAD

**Issue by samiwolf** [szaza/android-yolo-v2#1]
Hi. I tried to change the minSdkVersion to 23 but the app crashes. Camera2 API runs from SDK version 21. So, why is the app crashing? The error message is as follows - 

 java.lang.RuntimeException: Unable to start activity ComponentInfo{org.tensorflow.yolo/org.tensorflow.yolo.view.ClassifierActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class org.tensorflow.yolo.view.OverlayView
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3319)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
                      at android.app.ActivityThread.access$1100(ActivityThread.java:229)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:7325)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                   Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class org.tensorflow.yolo.view.OverlayView
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
                      at org.tensorflow.yolo.view.CameraConnectionFragment.onCreateView(CameraConnectionFragment.java:135)
                      at android.app.Fragment.performCreateView(Fragment.java:2281)
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:984)
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1164)
                      at android.app.BackStackRecord.run(BackStackRecord.java:793)
                      at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1557)
                      at android.app.FragmentController.execPendingActions(FragmentController.java:326)
                      at android.app.Activity.performStart(Activity.java:6942)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3276)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415) 
                      at android.app.ActivityThread.access$1100(ActivityThread.java:229) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:7325) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                   Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class org.tensorflow.yolo.view.OverlayView
                      at android.view.LayoutInflater.createView(LayoutInflater.java:657)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:527)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                      at org.tensorflow.yolo.view.CameraConnectionFragment.onCreateView(CameraConnectionFragment.java:135) 
                      at android.app.Fragment.performCreateView(Fragment.java:2281) 
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:984) 
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1164) 
                      at android.app.BackStackRecord.run(BackStackRecord.java:793) 
                      at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1557) 
                      at android.app.FragmentController.execPendingActions(FragmentController.java:326) 
                      at android.app.Activity.performStart(Activity.java:6942) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3276) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415) 
                      at android.app.ActivityThread.access$1100(ActivityThread.java:229) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:7325) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                   Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Constructor.newInstance(Native Method)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:631)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                      at org.tensorflow.yolo.view.CameraConnectionFragment.onCreateView(CameraConnectionFragment.java:135) 
                      at android.app.Fragment.performCreateView(Fragment.java:2281) 
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:984) 
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1164) 
                      at android.app.BackStackRecord.run(BackStackRecord.java:793) 
                      at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1557) 
                      at android.app.FragmentController.execPendingActions(FragmentController.java:326) 
                      at android.app.Activity.performStart(Activity.java:6942) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3276) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415) 
                      at android.app.ActivityThread.access$1100(ActivityThread.java:229) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:7325) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                   Caused by: java.lang.NoSuchMethodError: No virtual method lines()Ljava/util/stream/Stream; in class Ljava/io/BufferedReader; or its super classes (declaration of 'java.io.BufferedReader' appears in /system/framework/core-libart.jar)
                      at org.tensorflow.yolo.util.ClassAttrProvider.init(ClassAttrProvider.java:40)
                      at org.tensorflow.yolo.util.ClassAttrProvider.<init>(ClassAttrProvider.java:27)
                      at org.tensorflow.yolo.util.ClassAttrProvider.newInstance(ClassAttrProvider.java:32)
                      at org.tensorflow.yolo.view.OverlayView.<init>(OverlayView.java:40)
                      at java.lang.reflect.Constructor.newInstance(Native Method) 
                      at android.view.LayoutInflater.createView(LayoutInflater.java:631) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                      at org.tensorflow.yolo.view.CameraConnectionFragment.onCreateView(CameraConnectionFragment.java:135) 
                      at android.app.Fragment.performCreateView(Fragment.java:2281) 
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:984) 
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1164) 
                      at android.app.BackStackRecord.run(BackStackRecord.java:793) 
                      at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1557) 
                      at android.app.FragmentController.execPendingActions(FragmentController.java:326) 
                      at android.app.Activity.performStart(Activity.java:6942) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3276) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415) 
                      at android.app.ActivityThread.access$1100(ActivityThread.java:229) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:7325) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by szaza** [comment]
Hi,
Thank you for your feedback, I really appreciate it!
The problem is that I've used lambda expression in ClassAttrProvider.java line 40. You're absolutely right the Camera2 API is supported from API level 21, however the lambda expressions are supported only from API level 24. Initially I didn't plan to support the lower API levels, however right now I'm thinking on it. I planned to refactor the whole code, so probably I will add some backward compatibility also. I made a quick fix on the branch _API-level-23-compatibility_ for your problem. Could you please try it out?

**Comment by samiwolf** [comment]
Works just fine! Thanks!

**Comment by szaza** [comment]
You're welcome!

**Comment by xuzongping** [comment]
Hello, excuse me, I need to change my own dataset. How do I need to train it?
