### ISSUE TITLE
App crash on the simulator

### ISSUE THREAD

**Issue by derek-zr** [szaza/android-yolo-v2#24]
Hello，when i try to build and run the repo on the simulator(Genymotion, Nexus 5, API 23, Android 6.0). The app can get the camera image, but then quickly quit. I wonder if it's because the simulator or the code itself?

The error is like:
dequeueBuffer: createGraphicBuffer failed
can't dequeue multiple buffers without setting the buffer count
at android.hardware.camera2.legacy.SurfaceTextureRenderer.checkEglError(SurfaceTextureRenderer.java:487)
            at android.hardware.camera2.legacy.SurfaceTextureRenderer.swapBuffers(SurfaceTextureRenderer.java:480)
            at android.hardware.camera2.legacy.SurfaceTextureRenderer.drawIntoSurfaces(SurfaceTextureRenderer.java:681)
            at android.hardware.camera2.legacy.GLThreadManager$1.handleMessage(GLThreadManager.java:103)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by derek-zr** [comment]
@szaza

**Comment by derek-zr** [comment]
Closed. Use a real mobile phone can solve this. I search the error , and it may be the Camera2API and x86 simulator. So if you want to run it on the simulator, you need to change the code to CameraV1API.
