### ISSUE TITLE
unable to load custom pb "protobuff"

### ISSUE THREAD

**Issue by monupurohit** [szaza/android-yolo-v2#5]
Your code is working fine with your provided pb file for 20 objects.
I replaced your pb file with mine and keeping the same name.
replace the label content with my 3 object name.
And when tired to run the application with my pb file (created from tiny yolo voc - yolo v2) for 3 objects
Im unable to launch the application, getting error : Failed to load model 

Please suggest.

Regards
Purohit

Logs on the app : 

ava.lang.RuntimeException: Failed to load model from 'file:///android_asset/tiny-yolo-voc-graph.pb'
	at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:100)
	at org.tensorflow.yolo.TensorFlowImageRecognizer.create(TensorFlowImageRecognizer.java:42)
	at org.tensorflow.yolo.view.ClassifierActivity.onPreviewSizeChosen(ClassifierActivity.java:55)
	at org.tensorflow.yolo.view.CameraActivity.lambda$setFragment$0$CameraActivity(CameraActivity.java:116)
	at org.tensorflow.yolo.view.CameraActivity$$Lambda$0.onPreviewSizeChosen(Unknown Source)
	at org.tensorflow.yolo.view.CameraConnectionFragment.setUpCameraOutputs(CameraConnectionFragment.java:291)
	at org.tensorflow.yolo.view.CameraConnectionFragment.openCamera(CameraConnectionFragment.java:298)
	at org.tensorflow.yolo.view.CameraConnectionFragment.access$000(CameraConnectionFragment.java:52)
	at org.tensorflow.yolo.view.CameraConnectionFragment$1.onSurfaceTextureAvailable(CameraConnectionFragment.java:163)
	at android.view.TextureView.getHardwareLayer(TextureView.java:368)
	at android.view.View.updateDisplayListIfDirty(View.java:15191)
	at android.view.View.draw(View.java:15987)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
	at android.view.View.updateDisplayListIfDirty(View.java:15209)
	at android.view.View.draw(View.java:15987)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
	at android.view.View.draw(View.java:16220)
	at android.view.View.updateDisplayListIfDirty(View.java:15214)
	at android.view.View.draw(View.java:15987)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
	at android.view.View.updateDisplayListIfDirty(View.java:15209)
	at android.view.View.draw(View.java:15987)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
	at android.view.View.updateDisplayListIfDirty(View.java:15209)
	at android.view.View.draw(View.java:15987)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
	at android.view.View.draw(View.java:16220)
	at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
	at android.view.View.updateDisplayListIfDirty(View.java:15214)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:283)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:289)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:324)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2651)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2470)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2103)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1139)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6064)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
	at android.view.Choreographer.doCallbacks(Choreographer.java:672)
	at android.view.Choreographer.doFrame(Choreographer.java:608)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
	at android.os.Handler.handleCallback(Handler.java:742)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5571)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
Caused by: java.io.IOException: Not a valid TensorFlow Graph serialization: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: 0-convolutional = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true](Pad, 0-convolutional/filter). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	at org.tensorflow.contrib.android.TensorFlowInferenceInterface.loadGraph(TensorFlowInferenceInterface.java:392)
	at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:96)
	... 52 more

**Comment by szaza** [comment]
Hi Monu Purohit,

It seems for me that it did not found the protobuff file: ava.lang.RuntimeException: Failed to load model from 'file:///android_asset/tiny-yolo-voc-graph.pb'. 
Have you used the same file name? If not then please change the filename in the https://github.com/szaza/android-yolo-v2/blob/master/build.gradle and in the https://github.com/szaza/android-yolo-v2/blob/master/src/org/tensorflow/yolo/Config.java.

I would have some more questions:
* How you trained your model? Have you followed the description on my site: https://sites.google.com/view/tensorflow-example-java-api/complete-guide-to-train-yolo?
* Have you checked your model with DarkFlow: https://github.com/thtrieu/darkflow?
* If it still not works then can you please share your retrained model in order to check it?

Best regards,
  Zoltan

**Comment by BaptisteAmato** [comment]
Hi! Awesome work man :)
Same problem here though :(

2:39:10.540 15905-15905/org.tensorflow.yolo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.tensorflow.yolo, PID: 15905
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.tensorflow.yolo/org.tensorflow.yolo.view.MainActivity}: java.lang.RuntimeException: Failed to load model from 'file:///android_asset/tiny-yolo19.pb'
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3255)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3351)
        at android.app.ActivityThread.access$1100(ActivityThread.java:222)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7230)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
     Caused by: java.lang.RuntimeException: Failed to load model from 'file:///android_asset/tiny-yolo19.pb'
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:100)
        at org.tensorflow.yolo.TensorFlowImageRecognizer.create(TensorFlowImageRecognizer.java:43)
        at org.tensorflow.yolo.view.MainActivity.onCreate(MainActivity.java:43)
        at android.app.Activity.performCreate(Activity.java:6877)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3208)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3351) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:158) 
        at android.app.ActivityThread.main(ActivityThread.java:7230) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
     Caused by: java.io.IOException: Not a valid TensorFlow Graph serialization: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: 0-convolutional = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true](Pad, 0-convolutional/filter). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.loadGraph(TensorFlowInferenceInterface.java:392)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:96)
        at org.tensorflow.yolo.TensorFlowImageRecognizer.create(TensorFlowImageRecognizer.java:43)




I just wanted to know, are you sure Darkflow's "savepb" feature is working well? Indeed, even with Darkflow, when I try to load a pb with "pbLoad", anything gets detected, I need to add the "metaLoad" to get it work :s

**Comment by BaptisteAmato** [comment]
Just a quick question: in theory, should your code accept any model graph? For example, should we be able to use a full yolo v3 model?

**Comment by szaza** [comment]
No, unfortunately it supports only the YOLOv2 models.

**Comment by BaptisteAmato** [comment]
Ok; does it only support the tiny version or the full yolov2 model should be accepted? (Just in theory, because I don't manage to make my .pb file work for now anyway ^^')

**Comment by BaptisteAmato** [comment]
One thing to be noted: inspecting your .pb file and mine (generated by darkflow with --savepb command), I find differenced in the input tensor.
Commands:
```
import tensorflow as tf
g = tf.GraphDef()
g.ParseFromString(open("file.pb", "rb").read())
[n for n in g.node if n.name.find("input") != -1]
```

Output for your .pb:
```
[name: "input"
 op: "Placeholder"
 attr {
   key: "dtype"
   value {
     type: DT_FLOAT
   }
 }
 attr {
   key: "shape"
   value {
     shape {
       unknown_rank: true
     }
   }
 }]
```

Output for mine:
```
[name: "input"
 op: "Placeholder"
 attr {
   key: "dtype"
   value {
     type: DT_FLOAT
   }
 }
 attr {
   key: "shape"
   value {
     shape {
       dim {
         size: -1
       }
       dim {
         size: 416
       }
       dim {
         size: 416
       }
       dim {
         size: 3
       }
     }
   }
 }]
```

I wonder how you saved your protobuf file :o

**Comment by szaza** [comment]
It accepts both of them, however the mobile devices usually are not able to run the full YOLOv2, because it requires too much operations.
In these projects: 
- https://github.com/szaza/tensorflow-example-java
- https://github.com/szaza/tensorflow-java-examples-spring
I've used the same YOLO classifier and it worked with full YOLOv2 also.

**Comment by szaza** [comment]
I wrote an article about how I trained my models here: https://sites.google.com/view/tensorflow-example-java-api/complete-guide-to-train-yolo. Here you can find some interactive code examples also on Google Colaboratory, so you can execute them. Can you please guys send a link with your retrained models to the szabozoltanbors@gmail.com?

**Comment by BaptisteAmato** [comment]
Just sent you mine :)

**Comment by monupurohit** [comment]
Sure,
Im uploading it to wetransfer, will be done in couple of minutes.

Regards
Purohit

**Comment by szaza** [comment]
Thx, I'm going to find the problem. It will take some time.

**Comment by BaptisteAmato** [comment]
I read on some issues of Darkflow that generating the protobuf is not sufficient to make the model work on mobile applications, but it needs to be merged with the checkpoint.
@szaza did you only use the "savepb" command and used the generated .pb directly?

**Comment by szaza** [comment]
Yes, I only used the savepb without any optimization/quantization etc.

**Comment by BaptisteAmato** [comment]
Alright, weird...

**Comment by szaza** [comment]
Yes, it is weird. I've checked your pb file and for the first look it seems strange to me that it is 180Mb. Every time when I saved the tiny-yolo.pb file it was around 63Mb. I have to recheck the tutorial what I wrote. Have you used only the darkflow for the training or you trained with the darknet then converted the weights with the darkflow?

**Comment by BaptisteAmato** [comment]
I may have sent you the wrong files, resending you .pb and .meta files that are around 60Mo :)

**Comment by monupurohit** [comment]
I mail my model with wetransfer on your email id, let me know if you need any further data.

**Comment by monupurohit** [comment]
I was reading your  link  
https://sites.google.com/view/tensorflow-example-java-api/complete-guide-to-train-yolo 

I followed the same steps but for me with self.offset = 16 (./darkflow/utils/loader.py) pb file got created
no need to change it to "20".

Are you not using the meta file for creating the mobile application?

**Comment by BaptisteAmato** [comment]
@szaza I tried with your .pb at https://drive.google.com/drive/folders/1GfS1Yle7Xari1tRUEi2EDYedFteAOaoN and it does not work :o

**Comment by szaza** [comment]
@monupurohit thanks for the file I've got it.

_I followed the same steps but for me with self.offset = 16 (./darkflow/utils/loader.py) pb file got created
no need to change it to "20"._

I needed this change only when I trained my models with darknet and converted the weight files with darkflow. This change is not required if you trained your model with darkflow.

**Comment by BaptisteAmato** [comment]
I pulled master but it still does not work :s do I need to do anything else..?

**Comment by BaptisteAmato** [comment]
In the git log, I don't see any recent modification... The last one is:

```
commit a75d601095e5fde8e06db8e3e9eeb8f9bf0dde07 (HEAD -> master, origin/master, origin/HEAD)
Author: Zoltán Szabó <szaza@users.noreply.github.com>
Date:   Thu May 3 17:41:56 2018 +0300

    Update README.md
```

**Comment by szaza** [comment]
Hi all,
It seems that something went wrong yesterday when I pushed the modifications. I didn't observed it, sorry for it.
Now I pushed it again. The modifications are:
            dependencies { 
                compile 'org.tensorflow:tensorflow-android:1.2.0-preview' - removed
                compile 'org.tensorflow:tensorflow-android:1.6.0' - added
            } 
Could you please try again running the app with these changes?

**Comment by BaptisteAmato** [comment]
Alright :)
Working! I just tested with basic weights so no prediction is done, but no crash :) Thanks a lot man!

**Comment by szaza** [comment]
You're welcome!

**Comment by BaptisteAmato** [comment]
Just a question @szaza: with a full network (yolov2), I get an error "No OpKernel", do you know where it comes from?

**Comment by szaza** [comment]
The TensorFlow mobile edition doesn't support all the operations which are required for the full YOLOv2.
Probably you can find some more ideas to resolve it here: https://github.com/tensorflow/tensorflow/issues/10153.

**Comment by BaptisteAmato** [comment]
Oh ok, too bad ^^' thanks anyway!

**Comment by monupurohit** [comment]
Hello Zoltan

with the new dependencies for tensorflow version, this issue got fixed.
build.gradle
dependencies {
                compile 'org.tensorflow:tensorflow-android:1.6.0'
            }

I'm able to deploy and run the apk.

Great work !!
Many thanks..

However its a temporary fix, assuming if tomorrow a newer version comes say tensorflow-android:1.7.0
Again this apk will going to crash.
It will be great if your code fetch the latest available tensorflow-android version.

But I appreciate your efforts on this.
Keep the good work :)

**Comment by monupurohit** [comment]
Few queries : 
How to set the threshold value for this apk.
Whats your plan for Yolo V3 apk  🥇 🥇 🥇

**Comment by monupurohit** [comment]
I got the way to get the latest tensorflow android version : 

link : [https://www.tensorflow.org/mobile/android_build]
>>
dependencies {
    compile 'org.tensorflow:tensorflow-android:+'
}
This automatically downloads the latest stable version of TensorFlow as an AAR and installs it in your project.

It wil be great to put this instead of hardcoding to tensorflow-android:1.6.0

**Comment by szaza** [comment]
@monupurohit thanks for your advice I will adapt the code accordingly.
I would like to add support for Yolo V3, however I am very occupied right now. I have a full time job, I have to finish my dissertation thesis  and beside these I hold laboratories on the faculty. So, I will add the V3 support as soon as possible hopefully in the next few months.
Anyway guys, many thanks for your observations, advices and feedbacks and if you would like please join to the development, let's improve the code together.

**Comment by BaptisteAmato** [comment]
Thanks for your reactivity @szaza :) I'd be happy to help supporting other architectures like full yolo (maybe for single image detection, not real time) and tiny yolo v3. 
I don't really know how to do that though, but if you point me toward the right documentations/links and tell me what's the idea behind it, I'd like to help improving this repo ^^

**Comment by monupurohit** [comment]
I'm in.
We can start with tiny Yolo V3.
As mention from BaptisteAmato point us the documents/guide from where we can start.
not much experience with Android but we can give a shot.

**Comment by szaza** [comment]
The best starting point is the original yolov3 article what can be found here: https://arxiv.org/pdf/1804.02767.pdf. Tis site: https://towardsdatascience.com/yolo-v3-object-detection-53fb7d3bfe6b is also very helpful.
@BaptisteAmato I already tried to run full yolo on my phone for a single image detection, however my device ran out of memory. My mobile device has 2GB of memory and it was not enough. Probably a stronger device can run it.

**Comment by BaptisteAmato** [comment]
@szaza you tried to run full yolo on your phone, but you told me all the operations necessary to run full network were not implemented :0
I found a phone on which I can load the network, but do you have any idea how I can make it work with the full network?

**Comment by balaji199823** [comment]
> Hi all,
> It seems that something went wrong yesterday when I pushed the modifications. I didn't observed it, sorry for it.
> Now I pushed it again. The modifications are:
> dependencies {
> compile 'org.tensorflow:tensorflow-android:1.2.0-preview' - removed
> compile 'org.tensorflow:tensorflow-android:1.6.0' - added
> }
> Could you please try again running the app with these changes?

szaza sir, i m trying to work in android studio using your project 
i have build and run the apk using my .pb file but the apk wont start just stop automatically plz help me as soon as possible its my final year project i thought just replacing the .pb file would make the project but the apk is not working properly 
kindly plz help me sir
